version: "3.7"

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    depends_on:
      - fastapi
    ports:
      - 8082:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - custom

  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8000
    networks:
      - custom
    depends_on:
      - db
    environment:
      DATABASE_URI: $DATABASE_URI
    command:
      - "sh"
      - "-c"
      - "alembic upgrade head && gunicorn -c conf/gunicorn.conf.py 'src.beta.main.web_api:create_app()'"
  db:
    container_name: postgres
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
    networks:
      - custom
    ports:
      - "2344:${DB_PORT}"


networks:
  custom:
    driver: bridge